services:
  - type: worker
    name: telegram-lemonfox-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: true
      - key: LEMONFOX_API_KEY
        sync: true
